### ISSUE TITLE
Errors After Install and Run

### ISSUE THREAD

**Issue by turnerniles** [rbartoli/react-boilerplate#2]
After I run `npm i` and then `npm start` I get the errors below:

![image](https://cloud.githubusercontent.com/assets/8146241/17123368/2c818a2c-52b1-11e6-86f8-8df8fa59355a.png)

**Comment by turnerniles** [comment]
This is on Mac OSX

**Comment by rbartoli** [comment]
Hi Turner,

Thanks for taking the time to report an issue, however I cannot replicate it:

``` bash
npm i 
npm start
```

This is what I get:
![screenshot 2016-07-26 10 28 28](https://cloud.githubusercontent.com/assets/983189/17132932/d5cea7c6-531b-11e6-90ee-51d3d540df38.png)

It seems an error with Babel as you get the `Unexpected token =>` on the arrow function. Which version of Node have you got installed?

**Comment by rbartoli** [comment]
Are you using Node.js 5.10.1 also on your Mac?

**Comment by turnerniles** [comment]
I will check this issue tonight. Sorry only have my PC at the moment.

**Comment by turnerniles** [comment]
Hi Bartoli, I was using v0.12.2. I upgraded to v6.2.2 and it's working without errors now. Thank you.
