### ISSUE TITLE
Does Not Work on Windows

### ISSUE THREAD

**Issue by turnerniles** [rbartoli/react-boilerplate#3]
This is partly due to the environmental variable set in the package.json but also due to some other incompatibility that I'm not sure of.

**Comment by rbartoli** [comment]
Hi Turner,

The environmental variable is set only for the `build` npm script, so it shouldn't stop `npm start` from working.

I tried to start the boilerplate on a Windows 10 machine and it's working correctly (although I get some errors from `eslint` related to Windows line endings, but these are just related to code style and not functionality).

Do you get any errors? 
Which version of Windows and Node are you using?

**Comment by turnerniles** [comment]
Hi Riccardo, thank you for getting back to me so quickly! I am using Node v5.10.1. What version of node does the project require?

Below is the error I get. From googling it looks like a Node.js error.

``` bash
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\5.10.1\\node.exe" "C:\\nodejs\\5.10.1\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@0.4.0 start: `webpack-dev-server --history-api-fallback --hot --inline --progress`
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the react-boilerplate@0.4.0 start script 'webpack-dev-server --history-api-fallback --hot --inline --progress'.
```

**Comment by turnerniles** [comment]
Ok I figured out I was running the application from a different drive than the C drive. Working now. Thanks!
