### ISSUE TITLE
Less verbose webpack build?

### ISSUE THREAD

**Issue by hillscottc** [rbartoli/react-boilerplate#5]
Running `npm run build` spams you with warnings.

```
WARNING in bundle.js from UglifyJs
Condition always false [../~/fbjs/lib/invariant.js:26,0]
Dropping unreachable code [../~/fbjs/lib/invariant.js:27,0]
Condition always false [../~/fbjs/lib/warning.js:24,0]
...etc.
```

I'm looking for a way to turn this noise off. Calling webpack with `--no-info` or `--quiet` doesn't help. Hmm.

**Comment by hillscottc** [comment]
Still no luck. I expect it has something to do with  Uglify.js, but I can't find an explicit reference to uglify anywhere in the code. Tricky. Hmm.

**Comment by hillscottc** [comment]
I am discussing it with the webpack folks in this thread: https://github.com/webpack/webpack/issues/2352#issuecomment-274279180

**Comment by rbartoli** [comment]
That's probably the best place to discuss it. I've just subscribed to the conversation with the webpack-cli team.

**Comment by rbartoli** [comment]
I've got another similar boilerplate that is using webpack 2.2.0 and it seems that an option to suppress warnings and other types of output has been added to UglifyJS, and the output is all disabled by default. I've just tested this and it seems exactly what you want.

So as an option you can consider upgrading webpack to v2. I'm going to update the boilerplate as soon as webpack's team will start using [the latest tag](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#d799).
