### ISSUE TITLE
Spread operator ...

### ISSUE THREAD

**Issue by xfo** [rbartoli/react-boilerplate#6]
How to enable spread (...) es6 operator?
I use webpack-2 branch
```
ERROR in ./src/reducers/calendar.js
Module build failed: SyntaxError: ./src/reducers/calendar.js: Unexpected token (12:11)

  10 |  switch (action.type) {
  11 |          case actionTypes.SHIFT_CALENDAR_DAY_BACK:
> 12 |                  return  {...state, startDate: state.startDate - 1000 * 60 * 60 * 24}
     |                           ^
  13 |
  14 |          case actionTypes.SHIFT_CALENDAR_DAY_FORWARD:
  15 |                  return  {...state, startDate: state.startDate + 1000 * 60 * 60 * 24}

 @ ./src/reducers/index.js 9:16-37
```

**Comment by rbartoli** [comment]
@xfo Sorry for the late reply. I hope you sorted this already, however if that's not the case I've created a pull request so you can see what you need to add to enable the spread operator.

You can find it here: https://github.com/rbartoli/react-boilerplate/pull/7/files

I'm going to merge this in as soon as I've got time to update all the boilerplate's dependencies.
